language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
deploy:
  provider: heroku
  api_key:
    secure: RWgyjCyLsGbte2F5RlGkoof9ZmSnaYP+JGAsGG540dFNBqZcHhg5sqlgi53tNQUaTtlfZsOZHKmuOAWYwu9z9caOKRUy+CmMuWTGPYPCyR1+fUzqrY/q3cnJ+vKUWRZGaSdjGXOBHzNJyq3lTUhbzTSMoCy3h9tGMQCylKTQpGyLo4VsIy7kMKkyGb+jElkLhq89UuRoECcFhZKH/ulCgUjhcd9LDpqKgainbVT+ZvKA+8PZFzlgUdYH89O35MGh9xbXmydrqzLndKBUz2aLvCNRr4nQKZ/h6n2TYlWLiYWLpCkEty7Mqc7M08Sl8fgogJyhtKvJBYor2vrQBsJrxgH8yYTe5lUeCq2L50ru/PwwTGTK0W/R+YQvl2NCXCoLuNk0vLT8IBkABTNMpJKKgGHVdBVsFQoIe7PmVqCq2eB1KtzuQIi760AHNLY6qvS6gXKQMz2l0okLcA3SAvK0/0kmynXYz27lNM6JSleUaTeQNNtAhplt/4Yrg37aCnDHl+bKd0SPz2DWP3utdGtJH7Fhnn7pV7v66hljUoyMk+nPIJrq2tNYGQY8DLcau3NuuaXXF3gBwoJ08Xvc7/lAncd0HwDlHLCvHbA1Y6AwI9Z7ZZ3FHt92r2dLlpko/aCH1rof78x/gr+c/m6zszxw2P7JGnC2WIgGn9ubP4yeu0s=
app: flaskapptm
  on:
    repo: Lwando92 / flaskappteam
